language: cpp
matrix:
  include:
    - os: linux
      compiler: clang
      name: clang-ninja
      sudo: required
      env: TASK=clang
      dist: xenial
      cache: ccache
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - ninja-build
            - libglu1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - xorg-dev
            - libsdl2-dev
            - libglew-dev
            - libsndio-dev
            - libxkbcommon-dev
      script: ./travis.sh
    - os: linux
      compiler: gcc
      name: gcc-make
      sudo: required
      env: TASK=gcc
      dist: xenial
      cache: ccache
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - libglu1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - xorg-dev
            - libsdl2-dev
            - libglew-dev
            - libsndio-dev
            - libxkbcommon-dev
      script: ./travis.sh
    - os: linux
      name: format-check
      sudo: required
      env: TASK=clang-format
      dist: xenial
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7
          packages:
            - clang-format-7
      script: ./travis.sh
    - os: osx
      sudo: false
      osx_image: xcode10
      cache: ccache
      script:
        - ./travis.sh
